export const PODCAST_GET_PODCAST_LIST_BEGIN = 'PODCAST_GET_PODCAST_LIST_BEGIN';
export const PODCAST_GET_PODCAST_LIST_SUCCESS = 'PODCAST_GET_PODCAST_LIST_SUCCESS';
export const PODCAST_GET_PODCAST_LIST_FAILURE = 'PODCAST_GET_PODCAST_LIST_FAILURE';
export const PODCAST_GET_PODCAST_LIST_DISMISS_ERROR = 'PODCAST_GET_PODCAST_LIST_DISMISS_ERROR';

export const PODCAST_ADD_PODCAST_BEGIN = 'PODCAST_ADD_PODCAST_BEGIN';
export const PODCAST_ADD_PODCAST_SUCCESS =   'PODCAST_ADD_PODCAST_SUCCESS';
export const PODCAST_ADD_PODCAST_FAILURE =   'PODCAST_ADD_PODCAST_FAILURE';
export const PODCAST_ADD_PODCAST_DISMISS_ERROR =   'PODCAST_ADD_PODCAST_DISMISS_ERROR';

export const PODCAST_GET_PODCAST_BY_ID_BEGIN = 'PODCAST_GET_PODCAST_BY_ID_BEGIN';
export const PODCAST_GET_PODCAST_BY_ID_SUCCESS =   'PODCAST_GET_PODCAST_BY_ID_SUCCESS';
export const PODCAST_GET_PODCAST_BY_ID_FAILURE =   'PODCAST_GET_PODCAST_BY_ID_FAILURE';
export const PODCAST_GET_PODCAST_BY_ID_DISMISS_ERROR =   'PODCAST_GET_PODCAST_BY_ID_DISMISS_ERROR';

export const PODCAST_UPDATE_PODCAST_BEGIN = 'PODCAST_UPDATE_PODCAST_BEGIN'
export const PODCAST_UPDATE_PODCAST_SUCCESS = 'PODCAST_UPDATE_PODCAST_SUCCESS'
export const PODCAST_UPDATE_PODCAST_FAILURE = 'PODCAST_UPDATE_PODCAST_FAILURE'
export const PODCAST_UPDATE_PODCAST_DISMISS_ERROR = 'PODCAST_UPDATE_PODCAST_DISMISS_ERROR'

export const PODCAST_SET_CURRENT_PODCAST = 'PODCAST_SET_CURRENT_PODCAST';
