export const PODCAST_GET_PODCAST_BEGIN = 'PODCAST_GET_PODCAST_BEGIN';
export const PODCAST_GET_PODCAST_SUCCESS = 'PODCAST_GET_PODCAST_SUCCESS';
export const PODCAST_GET_PODCAST_FAILURE = 'PODCAST_GET_PODCAST_FAILURE';
export const PODCAST_GET_PODCAST_DISMISS_ERROR = 'PODCAST_GET_PODCAST_DISMISS_ERROR';
