export const GET_LIST_TICKET_BEGIN = 'GET_LIST_TICKET_BEGIN';
export const GET_LIST_TICKET_SUCCESS = 'GET_LIST_TICKET_SUCCESS';
export const GET_LIST_TICKET_FAILURE = 'GET_LIST_TICKET_FAILURE';
export const GET_LIST_TICKET_DISMISS_ERROR = 'GET_LIST_TICKET_DISMISS_ERROR';

export const GET_TICKET_ID_BEGIN = 'GET_TICKET_ID_BEGIN';
export const GET_TICKET_ID_SUCCESS = 'GET_TICKET_ID_SUCCESS';
export const GET_TICKET_ID_FAILURE = 'GET_TICKET_ID_FAILURE';
export const GET_TICKET_ID_DISMISS_ERROR = 'GET_TICKET_ID_DISMISS_ERROR';