export const USER_CREATE_USER_BEGIN = 'USER_CREATE_USER_BEGIN';
export const USER_CREATE_USER_SUCCESS = 'USER_CREATE_USER_SUCCESS';
export const USER_CREATE_USER_FAILURE = 'USER_CREATE_USER_FAILURE';
export const USER_CREATE_USER_DISMISS_ERROR = 'USER_CREATE_USER_DISMISS_ERROR';

export const USER_GET_USER_BEGIN = 'USER_GET_USER_BEGIN';
export const USER_GET_USER_SUCCESS = 'USER_GET_USER_SUCCESS';
export const USER_GET_USER_FAILURE = 'USER_GET_USER_FAILURE';
export const USER_GET_USER_DISMISS_ERROR = 'USER_GET_USER_DISMISS_ERROR';

export const USER_UPDATE_USER_BEGIN = 'USER_UPDATE_USER_BEGIN';
export const USER_UPDATE_USER_SUCCESS = 'USER_UPDATE_USER_SUCCESS';
export const USER_UPDATE_USER_FAILURE = 'USER_UPDATE_USER_FAILURE';
export const USER_UPDATE_USER_DISMISS_ERROR = 'USER_UPDATE_USER_DISMISS_ERROR';

export const USER_DELETE_USER_BEGIN = 'USER_DELETE_USER_BEGIN';
export const USER_DELETE_USER_SUCCESS = 'USER_DELETE_USER_SUCCESS';
export const USER_DELETE_USER_FAILURE = 'USER_DELETE_USER_FAILURE';
export const USER_DELETE_USER_DISMISS_ERROR = 'USER_DELETE_USER_DISMISS_ERROR';

export const USER_FORGOT_PASSWORD_BEGIN = 'USER_FORGOT_PASSWORD_BEGIN';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAILURE = 'USER_FORGOT_PASSWORD_FAILURE';
export const USER_FORGOT_PASSWORD_DISMISS_ERROR = 'USER_FORGOT_PASSWORD_DISMISS_ERROR';

export const USER_CHANGE_PASSWORD_BEGIN = 'USER_CHANGE_PASSWORD_BEGIN';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAILURE = 'USER_CHANGE_PASSWORD_FAILURE';
export const USER_CHANGE_PASSWORD_DISMISS_ERROR = 'USER_CHANGE_PASSWORD_DISMISS_ERROR';

export const GET_PROFIL_BEGIN = 'GET_PROFIL_BEGIN';
export const GET_PROFIL_SUCCESS = 'GET_PROFIL_SUCCESS';
export const GET_PROFIL_FAILURE = 'GET_PROFIL_FAILURE';
export const GET_PROFIL_DISMISS_ERROR = 'GET_PROFIL_DISMISS_ERROR';

export const USER_SET_CURRENT = 'USER_SET_CURRENT';