export const CUSTOMER_CREATE_CUSTOMER_BEGIN = 'CUSTOMER_SET_CUSTOMER_BEGIN';
export const CUSTOMER_CREATE_CUSTOMER_SUCCESS = 'CUSTOMER_CREATE_CUSTOMER_SUCCESS';
export const CUSTOMER_CREATE_CUSTOMER_FAILURE = 'CUSTOMER_CREATE_CUSTOMER_FAILURE';
export const CUSTOMER_CREATE_CUSTOMER_DISMISS_ERROR = 'CUSTOMER_CREATE_CUSTOMER_DISMISS_ERROR';

export const CUSTOMER_GET_CUSTOMER_BEGIN = 'CUSTOMER_GET_CUSTOMER_BEGIN';
export const CUSTOMER_GET_CUSTOMER_SUCCESS = 'CUSTOMER_GET_CUSTOMER_SUCCESS';
export const CUSTOMER_GET_CUSTOMER_FAILURE = 'CUSTOMER_GET_CUSTOMER_FAILURE';
export const CUSTOMER_GET_CUSTOMER_DISMISS_ERROR = 'CUSTOMER_GET_CUSTOMER_DISMISS_ERROR';

export const CUSTOMER_UPDATE_CUSTOMER_BEGIN = 'CUSTOMER_UPDATE_CUSTOMER_BEGIN';
export const CUSTOMER_UPDATE_CUSTOMER_SUCCESS = 'CUSTOMER_UPDATE_CUSTOMER_SUCCESS';
export const CUSTOMER_UPDATE_CUSTOMER_FAILURE = 'CUSTOMER_UPDATE_CUSTOMER_FAILURE';
export const CUSTOMER_UPDATE_CUSTOMER_DISMISS_ERROR = 'CUSTOMER_UPDATE_CUSTOMER_DISMISS_ERROR';

export const CUSTOMER_DELETE_CUSTOMER_BEGIN = 'CUSTOMER_DELETE_CUSTOMER_BEGIN';
export const CUSTOMER_DELETE_CUSTOMER_SUCCESS = 'CUSTOMER_DELETE_CUSTOMER_SUCCESS';
export const CUSTOMER_DELETE_CUSTOMER_FAILURE = 'CUSTOMER_DELETE_CUSTOMER_FAILURE';
export const CUSTOMER_DELETE_CUSTOMER_DISMISS_ERROR = 'CUSTOMER_DELETE_CUSTOMER_DISMISS_ERROR';

export const CUSTOMER_SET_CURRENT = 'CUSTOMER_SET_CURRENT';