export const AUTH_LOGIN_BEGIN = 'AUTH_LOGIN_BEGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGIN_DISMISS_ERROR = 'AUTH_LOGIN_DISMISS_ERROR';

export const AUTH_LOGOUT_BEGIN = 'AUTH_LOGOUT_BEGIN';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';
export const AUTH_LOGOUT_DISMISS_ERROR = 'AUTH_LOGOUT_DISMISS_ERROR';

export const AUTH_REFRESH_BEGIN = 'AUTH_REFRESH_BEGIN';
export const AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS';
export const AUTH_REFRESH_FAILURE = 'AUTH_REFRESH_FAILURE';
export const AUTH_REFRESH_DISMISS_ERROR = 'AUTH_REFRESH_DISMISS_ERROR';

export const AUTH_CAPTCHA_BEGIN = 'AUTH_CAPTCHA_BEGIN';
export const AUTH_CAPTCHA_SUCCESS = 'AUTH_CAPTCHA_SUCCESS';
export const AUTH_CAPTCHA_FAILURE = 'AUTH_CAPTCHA_FAILURE';
export const AUTH_CAPTCHA_DISMISS_ERROR = 'AUTH_CAPTCHA_DISMISS_ERROR';